---

- name: Create ~/.opt
  file:
    path: "{{ optdir }}"
    state: directory
    mode: 0755

- name: Create applications directory
  file:
    path: "{{ ansible_user_dir }}/.local/share/applications"
    state: directory
    mode: 0755

- include: kitty.yml
