---
   
- name: Install setup tools
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ setup_tools }}"

- name: Add Syncthing release PGP keys
  apt_key: 
    url: https://syncthing.net/release-key.txt
    state: present

- name: Add Syncthing stable repo
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present
    filename: syncthing

- name: Add VSCodium PGP keys
  apt_key: 
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    state: present

- name: Add VSCodium repo
  apt_repository:
    repo: deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main
    state: present
    filename: vscodium

- name: Add Nodesource PGP keys
  apt_key: 
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add Nodejs 15.x repo
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: nodesource
    loop:
      - deb https://deb.nodesource.com/node_14.x focal main
      - deb-src https://deb.nodesource.com/node_14.x focal main

- name: Add Yarn GPG keys
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add Yarn repo
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
    filename: yarn

# - name: Add Lutris PPA
#  apt_repository:
#    repo:  ppa:lutris-team/lutris
#    state: present
#    filename: lutris

- name: Add HashiCorp PGP key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp repo
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp

- name: apt update
  apt:
    update_cache: yes

- name: Install CLI tools and utilities
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ tools_utilities }}"

- name: Install dev tools
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ dev_tools }}"

- name: Install firmware and tools
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ firmware }}"

- name: Install desktop applications
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ desktop_apps }}"

- name: Install fonts and themes
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ fonts_themes }}"

- name: Update all packages
  apt:
    name: "*"
    state: latest
